update parameters for node and domains
autonomys/infra pull request #235
Opened 2024-01-12 14:28 UTC by DaMandal0rian

This PR updates the parameters for consensus node and domain nodes respective of the cli changes in [#2408](https://github.com/subspace/subspace/pull/2408) and [#2412](https://github.com/subspace/subspace/pull/2412)

2024-01-12 14:43 UTC, DaMandal0rian commented
closes #235

2024-01-12 23:54 UTC, nazar-pc requested changes
Commented on typos. Also this is only applicable for upcoming devnet/Gemini 3h, 3g and previous networks should continue to use old format and we will want to keep them running, not sure if this is taken into consideration in this PR.

> closes https://github.com/subspace/infra/pull/235

It only works when in the original PR message, not in comments.

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_bootstrap_node_compose_file.sh
> +      "--prometheus-listen-on", "9615",
Linsten on for Prometheus endpoint is `IP:port` format

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_bootstrap_node_evm_compose_file.sh
> +      echo '      "--rpc-listen-on", "8944",'
Listen on for RPC endpoint is in `IP:port` format

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_bootstrap_node_evm_compose_file.sh
> +      echo '      "--domain-id=${DOMAIN_ID}",'
```suggestion
      echo '      "--domain-id", "${DOMAIN_ID}",'
```

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_bootstrap_node_evm_compose_file.sh
>        echo '      "--base-path", "/var/subspace/core_${DOMAIN_LABEL}_domain",'
If this is a container, why do you have this custom path rather than `/var/subspace`?

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_domain_node_compose_file.sh
> +      "--rpc-methods", "auto",
`auto` is the default, either remove it or use this explicitly:
```suggestion
      "--rpc-methods", "safe",
```

2024-01-12 23:54 UTC, nazar-pc commented on aws/network-primitives/scripts/create_domain_node_compose_file.sh
> +      "--rpc-listen-on",
Value is missing for this argument

2024-01-14 13:11 UTC, DaMandal0rian commented
Yes, i have created a branch for gemini-3g, these changes will only be applicable to devnet and gemini-3h.

2024-01-14 13:13 UTC, nazar-pc commented
> Yes, i have created a branch for gemini-3g, these changes will only be applicable to devnet and gemini-3h.

Hm... that is a bit confusing, I expect everything we have deployed (at least production) to run of the main branch, not some custom branches.

2024-01-14 13:15 UTC, DaMandal0rian commented
> > Yes, i have created a branch for gemini-3g, these changes will only be applicable to devnet and gemini-3h.
> 
> Hm... that is a bit confusing, I expect everything we have deployed (at least production) to run of the main branch, not some custom branches.

This PR can be merged on to main, and not affect the state of gemini-3g. I was just keeping a branch for gemini-3g until it's discontinued.

2024-01-14 13:17 UTC, nazar-pc commented
> This PR can be merged on to main, and not affect the state of gemini-3g. I was just keeping a branch for gemini-3g until it's discontinued.

3g, just like other previous networks, will be running for a while to leave RPC available. And in case we need to move it to another machine or change number of instances we will need to have a working deployment.

2024-01-30 12:46 UTC, nazar-pc approved these changes
Approving, but I didn't actually review anything since last time.

The way I expect such PRs to be structured:
1) Move support of existing network to a separate directory (BTW `-archive` is not a great name because we will likely have multiple of these, will you call the next one `-archive-2`?)
2) Then new stuff are instroduced

Instead existing code is updated in-place, then supposedly old version is copy-pasted into new directory and then a few more commits with merges and some other changes are added on top. With all of the force-pushes and thousands of lines of code I do not have patience to re-review every single line again.

2024-01-30 13:21 UTC, merged